enrichment_tables:
  geo_ip_db:
    type: mmdb
    path: /data/GeoLite2-City.mmdb
    locale: en
  threat_ip_csv:
    type: file
    file:
      encoding:
        include_headers: true
        type: csv
      path: /data/threat_ip.csv
sources:
  source_enrich_3:
    type: kafka
    bootstrap_servers: broker1:29092
    group_id: enrich_3
    topics:
    - enrich_3
    auto_offset_reset: earliest
    acknowledgements:
      enabled: true
    decoding:
      codec: json
    drain_timeout_ms: 2500
    fetch_wait_max_ms: 100
transforms:
  enrich_window_log_input-3:
    type: remap
    inputs:
    - source_enrich_3
    drop_on_abort: true
    source: |
      threat = false
      for_each(keys(.)) -> |_, key| {
        if (contains(key, "ip")) {
          value = get!(., [key])
          if (is_ipv4(to_string!(value))) {
            # Check threat IP
            check, _ = get_enrichment_table_record("threat_ip_csv", {"ip":value})
            if (check != {}) {
              if (threat == false) {
                threat = true
              }
            }
          }
        }
      }
      .threat_ip = threat
      del(.message_key)
      del(.offset)
      del(.partition)
      del(.topic)
      del(.source_type)
      del(.headers)
  aws_s3_route:
    type: remap
    inputs:
    - enrich_window_log_input-3
    source: |
      true

  elasticsearch_route:
    type: remap
    inputs:
    - enrich_window_log_input-3
    source: |
      true

  elasticsearch_window_log_input-3:
    type: remap
    inputs:
    - elasticsearch_route
    source: |
      del(.message)
      .log_type == "error_log"
sinks:
  sink_elasticsearch_window_log_input-3:
    type: elasticsearch
    inputs:
    - elasticsearch_window_log_input-3
    endpoint: http://elasticsearch:9200
    api_version: auto
    batch:
      max_events: 10
      timeout_secs: 10
    buffer:
      type: disk
      max_size: 268435488
      when_full: block
    mode: bulk
    bulk:
      action: index
      index: "window_log"
      template_fallback_index: "default_log"
    distribution:
      retry_initial_backoff_secs: 1
      retry_max_duration_secs: 3600
