sources:
  source_window_log_input-3:
    type: kafka
    bootstrap_servers: broker1:29092
    group_id: window_log
    topics:
    - window_log
    auto_offset_reset: earliest
    acknowledgements:
      enabled: true
    decoding:
      codec: bytes
    drain_timeout_ms: 2500
    fetch_wait_max_ms: 100
transforms:
  parse_window_log_input-3:
    type: remap
    inputs:
    - source_window_log_input-3
    drop_on_abort: true
    source: |
      .message = decode_charset!(.message, "utf-8")
      .log_type = "window_log"
      check1 = parse_xml!(.message)
              
      data_info = check1.Event.EventData.Data
      for_each(array!(data_info)) -> |_, item| {
        key = item."@Name"
        value = item.text
        . = set!(., [key], value)
      }
              
      system_info = check1.Event.System
      system_object = flatten!(system_info, "_")
      key_array = keys(system_object) 
      for_each(key_array) -> |_, key| {
        value = get!(system_object, [key])
        . = set!(., [key], value)
      }

      . = map_keys(.) -> |key| {
        key = replace(key, "@", "")
        key = snakecase(key)
      }
      del(.message)
      .time_created_system_time = parse_timestamp!(.time_created_system_time, "%+")
      .time_created_system_time = format_timestamp!(.time_created_system_time, "%Y-%m-%d %H:%M:%S")

  split_window_log_input-3:
    type: exclusive_route
    inputs:
    - parse_window_log_input-3
    routes:
    - name: "sample"
      condition:
        type: vrl
        source: |
          to_int!(.event_id) == 4634 # Logout

    - name: "dangerous"
      condition:
        type: vrl
        source: |
          to_int!(.event_id) == 4625 || to_int!(.event_id) == 4723
          # Failed login                 # Change password

    - name: "dedupe"
      condition:
        type: vrl
        source: |
          true
  sample_split_window_log_input-3:
    type: sample
    inputs:
    - split_window_log_input-3.sample
    ratio: 0.2
    sample_rate_key: ""
  dedupe_split_window_log_input-3:
    type: dedupe
    inputs:
    - split_window_log_input-3.dedupe
    cache:
      num_events: 1000
    fields:
      match:
      - ip_address
      - logon_type
      - workstation_name
      - target_user_name
sinks:
  console_3:
    type: console
    inputs:
    - split_window_log_input-3.dangerous
    - sample_split_window_log_input-3
    - dedupe_split_window_log_input-3
    target: stdout
    encoding:
      codec: json
  kafka_3:
    type: kafka
    inputs:
    - split_window_log_input-3.dangerous
    - sample_split_window_log_input-3
    - dedupe_split_window_log_input-3
    bootstrap_servers: broker1:29092
    topic: enrich_3
    encoding:
      codec: json
    buffer:
      type: disk
      max_size: 268435490
      when_full: block
