sources:
  source_cisco_log_input-1:
    type: kafka
    bootstrap_servers: broker1:29092
    group_id: cisco_log
    topics:
    - cisco_log
    auto_offset_reset: earliest
    acknowledgements:
      enabled: true
    decoding:
      codec: bytes
    drain_timeout_ms: 2500
    fetch_wait_max_ms: 100
  source_access_log_input-2:
    type: kafka
    bootstrap_servers: broker1:29092
    group_id: access_log
    topics:
    - access_log
    auto_offset_reset: earliest
    acknowledgements:
      enabled: true
    decoding:
      codec: bytes
    drain_timeout_ms: 2500
    fetch_wait_max_ms: 100
transforms:
  parse_cisco_log_input-1:
    type: remap
    inputs:
    - source_cisco_log_input-1
    drop_on_abort: true
    source: |
      .message = decode_charset!(.message, "utf-8")
      .log_type = "cisco_log"
      check1 = parse_regex!(.message, r'%ASA-(?P<severity>\d+)-.+') 
      if (to_int!(check1.severity) == 7) {
        .severity = check1.severity
        check2 = parse_regex!(.message, r'%ASA-(?P<severity>\d+)-(?P<message_id>\d+): (?P<message_text>.+)')
        .message_text = check2.message_text
        .message_id = check2.message_id
      } else {
        .severity = check1.severity
        check2 = parse_regex!(.message, r'%ASA-(?P<severity>\d+)-(?P<message_id>\d+): (?P<message_text>.+)')
        .message_id = check2.message_id
        if (match(check2.message_text, r'Teardown .+')) {
          .event_type = "connection_teardown"
          check3 = parse_regex!(check2.message_text, r'Teardown (?P<protocol>\w+) connection (?P<conn_id>\d+) for (?P<src_zone>\w+):(?P<src_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<src_port>\d+) to (?P<dst_zone>\w+):(?P<dst_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<dst_port>\d+) duration (?P<duration>\d{1,2}(?:\:\d{1,2}){2}) bytes (?P<bytes>\d+)')
          .protocol = check3.protocol
          .conn_id = check3.conn_id
          .src_zone = check3.src_zone
          .src_ip = check3.src_ip
          .src_port = check3.src_port
          .dst_zone = check3.dst_zone
          .dst_ip = check3.dst_ip
          .dst_port = check3.dst_port
          .duration = check3.duration
          .bytes = check3.bytes
        } else if (match(check2.message_text, r'Deny .+')) {
          .event_type = "connection_denied"
          check3 = parse_regex!(check2.message_text, r'Deny (?P<protocol>\w+) src (?P<src_zone>\w+):(?P<src_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<src_port>\d+) dst (?P<dst_zone>\w+):(?P<dst_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<dst_port>\d+) by access-group "(?P<access_group>[^"]+)"')
          .protocol = check3.protocol
          .src_zone = check3.src_zone
          .src_ip = check3.src_ip
          .src_port = check3.src_port
          .dst_zone = check3.dst_zone
          .dst_ip = check3.dst_ip
          .dst_port = check3.dst_port
          .access_group = check3.access_group
        } else if (match(check2.message_text, r'Built dynamic .+')) {
          .event_type = "nat_translation"
          check3 = parse_regex!(check2.message_text, r'Built dynamic (?P<protocol>\w+) translation from (?P<src_zone>\w+):(?P<src_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<src_port>\d+) to (?P<dst_zone>\w+):(?P<dst_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<dst_port>\d+)')
          .protocol = check3.protocol
          .src_zone = check3.src_zone
          .src_ip = check3.src_ip
          .src_port = check3.src_port
          .dst_zone = check3.dst_zone
          .dst_ip = check3.dst_ip
          .dst_port = check3.dst_port
        } else if (match(check2.message_text, r'Built ICMP connection .+')) {
          .event_type = "icmp_connection"
          check3 = parse_regex!(check2.message_text, r'Built ICMP connection for faddr (?P<dst_ip>\d{1,3}(\.\d{1,3}){3})/0 gaddr (?P<nat_ip>\d{1,3}(\.\d{1,3}){3})/0 laddr (?P<src_ip>\d{1,3}(\.\d{1,3}){3})/0')
          .dst_ip = check3.dst_ip
          .nat_ip = check3.nat_ip
          .src_ip = check3.src_ip
        } else if (match(check2.message_text, r'Built \w+ \w+ connection .+')) {
          .event_type = "connection_build"
          check3 = parse_regex!(check2.message_text, r'Built (?P<direction>\w+) (?P<protocol>\w+) connection (?P<conn_id>\d+) for (?P<src_zone>\w+):(?P<src_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<src_port>\d+)(?: \((?P<nat_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<nat_port>\d+)\))? to (?P<dst_zone>\w+):(?P<dst_ip>\d{1,3}(?:\.\d{1,3}){3})/(?P<dst_port>\d+)')
          .protocol = check3.protocol
          .conn_id = check3.conn_id
          .src_zone = check3.src_zone
          .src_ip = check3.src_ip
          .src_port = check3.src_port
          .dst_zone = check3.dst_zone
          .dst_ip = check3.dst_ip
          .dst_port = check3.dst_port

          if (!is_null(check3.nat_ip)) {
            .nat_ip = check3.nat_ip
            .nat_port = check3.nat_port
          }
        }
        
      }
  split_cisco_log_input-1:
    type: exclusive_route
    inputs:
    - parse_cisco_log_input-1
    routes:
    - name: "sample"
      condition:
        type: vrl
        source: |
          to_int!(.severity) == 7
    - name: "dangerous"
      condition:
        type: vrl
        source: |
          string!(.event_type) == "connection_denied" || string!(.event_type) == "connection_teardown"
    - name: "dedupe"
      condition:
        type: vrl
        source: |
          true
  sample_split_cisco_log_input-1:
    type: sample
    inputs:
    - split_cisco_log_input-1.sample
    ratio: 0.2
    sample_rate_key: ""
  dedupe_split_cisco_log_input-1:
    type: dedupe
    inputs:
    - split_cisco_log_input-1.dedupe
    cache:
      num_events: 10000
    fields:
      match:
      - severity
      - event_type
      - src_ip
      - dst_ip
  parse_access_log_input-2:
    type: remap
    inputs:
    - source_access_log_input-2
    drop_on_abort: true
    source: |
      .message = decode_charset!(.message, "utf-8")
      .log_type = "access_log"
      check1 = parse_regex!(.message, r'(?P<ip>\d{1,3}(?:\.\d{1,3}){3}) - - \[(?P<timestamp>[0-9/\:\+\- ]+)\] \"(?P<method>\w+) (?P<url>[^ ]+) (?P<protocol>[\w/\.]+)\" (?P<status>\d+) (?P<bytes>\d+) \"(?P<user_agent>[^"]+)\" \"(?P<refer>[^"]+)\"')
      .ip = check1.ip
      .timestamp = check1.timestamp
      .method = check1.method
      .url = check1.url
      .protocol = check1.protocol
      .status = check1.status
      .bytes = check1.bytes
      .user_agent = check1.user_agent
      .refer = check1.refer
  split_access_log_input-2:
    type: exclusive_route
    inputs:
    - parse_access_log_input-2
    routes:
    - name: "sample"
      condition:
        type: "vrl"
        source: |
          statics = [ ".html", ".htm", ".css", ".js", ".mjs", ".jsx", ".tsx", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif", ".svg", ".ico", ".bmp", ".tiff", ".mp3", ".wav", ".ogg", ".mp4", ".webm", ".mov", ".avi", ".mkv", ".woff", ".woff2", ".ttf", ".otf", ".eot", ".json", ".xml", ".txt",]
          check_url = false
          for_each(statics) -> |_, static| {
            if (contains(string!(.url), static)) {
              check_url = true
            }
          }
          check_url
    - name: "dangerous"
      condition:
        type: "vrl"
        source: |
          methods = ["POST", "PUT", "DELETE"]
          check_method = false
          check_status = false

          for_each(methods) -> |_, refer| {
            if contains(string!(.method), refer) {
              check_method = true
            }
          }
          check_status = to_int!(.status) >= 400

          check_method || check_status 

    - name: "dedupe"
      condition:
        type: "vrl"
        source: |
          true
  sample_split_access_log_input-2:
    type: sample
    inputs:
    - split_access_log_input-2.sample
    ratio: 0.2
    sample_rate_key: ""
  dedupe_split_access_log_input-2:
    type: dedupe
    inputs:
    - split_access_log_input-2.dedupe
    cache:
      num_events: 5000
    fields:
      match:
      - method
      - status
      - url
      - ip
sinks:
  console_1:
    type: console
    inputs:
    - split_cisco_log_input-1.dangerous
    - sample_split_cisco_log_input-1
    - dedupe_split_cisco_log_input-1
    - split_access_log_input-2.dangerous
    - sample_split_access_log_input-2
    - dedupe_split_access_log_input-2
    target: stdout
    encoding:
      codec: json
  kafka_1:
    type: kafka
    inputs:
    - split_cisco_log_input-1.dangerous
    - sample_split_cisco_log_input-1
    - dedupe_split_cisco_log_input-1
    - split_access_log_input-2.dangerous
    - sample_split_access_log_input-2
    - dedupe_split_access_log_input-2
    bootstrap_servers: broker1:29092
    topic: enrich_1
    encoding:
      codec: json
    buffer:
      type: disk
      max_size: 268435490
      when_full: block
