sources:
  source_id_1:
    type: kafka
    bootstrap_servers: broker1:29092,broker2:29092,broker3:29092
    group_id: test1
    topics:
      - window_log
    auto_offset_reset: earliest
    decoding:
      codec: bytes
    drain_timeout_ms: 2500
    fetch_wait_max_ms: 100

transforms:
  transform_id_1:
    type: remap
    inputs:
      - source_id_1
    drop_on_abort: true
    source: |
      .message = decode_charset!(.message, "utf-8")
      .check = "health"
      check1 = parse_xml!(.message)
      del(.message)
              
      data_info = check1.Event.EventData.Data
      for_each(array!(data_info)) -> |_, item| {
        key = item."@Name"
        value = item.text
        . = set!(., [key], value)
      }
              
      system_info = check1.Event.System
      system_object = flatten!(system_info)
      key_array = keys(system_object) 
      for_each(key_array) -> |_, key| {
        value = get!(system_object, [key])
        . = set!(., [key], value)
      }
      
      . = map_keys(.) -> |key| {
        key = replace(key, "@", "")
        key = replace(key, ".", "")
        key = snakecase(key)
      }

  transform_route_1:
    type: exclusive_route
    inputs:
      - transform_id_1
    routes:
      - name: "reduce"
        condition:
          type: vrl
          source: |
            to_int!(.event_id) == 4634 # Logout

      - name: "dangerous"
        condition:
          type: vrl
          source: |
            to_int!(.event_id) == 4625 || to_int!(.event_id) == 4723
            # Failed login                 # Change password

      - name: "dedupe"
        condition:
          type: vrl
          source: |
            true

  transform_reduce_1:
    type: filter
    inputs:
      - transform_route_1.reduce
    condition:
      type: vrl
      source: |
        random_int(0, 100) <= 20

  transform_dedupe_1:
    type: dedupe
    inputs:
      - transform_route_1.dedupe
    cache:
      num_events: 1000
    fields:
      match:
        - ip_address
        - logon_type
        - workstation_name
        - target_user_name

sinks:
  console_output:
    type: console
    inputs:
      - transform_dedupe_1
    target: stdout     # hoặc stderr
    encoding:
      codec: json      # hoặc "text" nếu bạn chỉ cần chuỗi trong .message



tests:
  - name: "Test reduce route"
    inputs:
      - insert_at: transform_id_1
        type: log
        log_fields:
          message: '<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing"/>
    <EventID>4634</EventID>
    <Level>0</Level>
    <TimeCreated SystemTime="2025-06-06T18:32:09.353Z"/>
    <EventRecordID>758706</EventRecordID>
    <Channel>Security</Channel>
    <Computer>kirlin.co</Computer>
  </System>
  <EventData>
    <Data Name="TargetUserName">theo.price</Data>
    <Data Name="TargetDomainName">WORKGROUP</Data>
    <Data Name="LogonID">0xacdc6</Data>
  </EventData>
</Event>'
    outputs:
      - extract_from: transform_route_1.reduce
        conditions:
          - type: vrl
            source: |
              assert_eq!(to_int!(.event_id), 4634, "Can be reduce")
  - name: "Test dangerous route"
    inputs:
      - insert_at: transform_id_1
        type: log
        log_fields:
          message: '<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing"/>
    <EventID>4625</EventID>
    <Level>0</Level>
    <TimeCreated SystemTime="2025-06-03T02:56:13.354Z"/>
    <EventRecordID>847193</EventRecordID>
    <Channel>Security</Channel>
    <Computer>vandervort.net</Computer>
  </System>
  <EventData>
    <Data Name="TargetUserName">wes.barton</Data>
    <Data Name="TargetDomainName">WORKGROUP</Data>
    <Data Name="Status">0xc000006a</Data>
    <Data Name="FailureReason">Unknown user name or bad password.</Data>
    <Data Name="IpAddress">203.49.28.141</Data>
    <Data Name="IpPort">57441</Data>
  </EventData>
</Event>'
    outputs:
      - extract_from: transform_route_1.dangerous
        conditions:
          - type: vrl
            source: |
              assert_eq!(to_int!(.event_id), 4625, "Can be reduce")
  - name: "Test dedupe route"
    inputs:
      - insert_at: transform_id_1
        type: log
        log_fields:
          message: '<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing"/>
    <EventID>4624</EventID>
    <Level>0</Level>
    <TimeCreated SystemTime="2025-06-05T18:15:47.354Z"/>
    <EventRecordID>660934</EventRecordID>
    <Channel>Security</Channel>
    <Computer>mcglynn.co</Computer>
  </System>
  <EventData>
    <Data Name="SubjectUserSid">S-1-5-18</Data>
    <Data Name="SubjectUserName">SYSTEM</Data>
    <Data Name="TargetUserName">dannie.mante</Data>
    <Data Name="TargetDomainName">WORKGROUP</Data>
    <Data Name="LogonType">3</Data>
    <Data Name="LogonProcessName">User32</Data>
    <Data Name="AuthenticationPackageName">Negotiate</Data>
    <Data Name="WorkstationName">mcglynn.co</Data>
    <Data Name="IpAddress">77.211.147.141</Data>
    <Data Name="IpPort">50698</Data>
    <Data Name="ProcessName">C:\\Windows\\System32\\winlogon.exe</Data>
  </EventData>
</Event>'
    outputs:
      - extract_from: transform_route_1.dedupe
        conditions:
          - type: vrl
            source: |
              assert_eq!(to_int!(.event_id), 4624, "Can be reduce")